# Application name
spring.application.name=car-rental-system

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/car_rental

spring.datasource.username=root

spring.datasource.password=Global@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate config
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.level.org.springframework.security=TRACE

# Server port (optional)
server.port=8080